create table if not exists public.api_keys (
  id bigint generated by default as identity primary key,
  key_hash text unique not null,
  name text not null default 'Customer',
  credits bigint not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists api_keys_hash_idx on public.api_keys(key_hash);

-- Recommended: disable direct client access; the Vercel server uses the service-role key.
alter table public.api_keys enable row level security;
